### ISSUE TITLE
Error when installed - ddrr.middleware.DebugRequestsResponses' isn't a subclass of AppConfig.

### ISSUE THREAD

**Issue by lanshark** [denizdogan/django-debug-requests-responses#17]
Installed with pip, put first line of INSTALLED_APPS.  Start the service, get this:

Traceback (most recent call last):
  File "/data/server/mobile-survey-server/./manage.py", line 19, in <module>
    raise e
  File "/data/server/mobile-survey-server/./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/data/server/mobile-survey-server/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/data/server/mobile-survey-server/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/data/server/mobile-survey-server/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/data/server/mobile-survey-server/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/data/server/mobile-survey-server/venv/lib/python3.10/site-packages/django/apps/config.py", line 229, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'ddrr.middleware.DebugRequestsResponses' isn't a subclass of AppConfig.

**Comment by denizdogan** [comment]
Hey @lanshark, thanks for the report.

I haven't touched this project in a while, but it seems like you added `"ddrr.middleware.DebugRequestsResponses"` to `INSTALLED_APPS`, which is incorrect.

You should put `"ddrr"` in `INSTALLED_APPS`, then `"ddrr.middleware.DebugRequestsResponses"` goes in `MIDDLEWARE`. 

Let me know if that helps!

**Comment by lanshark** [comment]
That worked - sorry for the panic!
